---
 - name: install httpd
   yum: name=httpd state=present   

 - name: install php
   yum: name={{item}} state=present
   with_items:
     - php
     - php-gd
     - php-mysql
 
 - name: start httpd service
   service: name=httpd state=started

 - name: modify welcome page
   template:
     src: welcome.conf.j2
     dest: /etc/httpd/conf.d/welcome.conf

 - name: modify configuration file
   template:
     src: httpd.conf.j2
     dest: /etc/httpd/conf/httpd.conf
   notify: restart_http

 - name: allow firewall
   firewalld: port=18080/tcp permanent=true state=enabled

 - name: firewalld_reload
   service: name=firewalld state=restarted

 - name: install nfs utils
   yum: name=nfs-utils state=present

 - name: enable nfs service
   shell: systemctl enable nfs-server.service

 - name: start nfs service
   shell: systemctl start nfs-server.service 

 - name: mount nfs share
   mount: name=/var/www/html/ src=www.lab.com:/var/wordpress.files fstype=nfs4 state=mounted
