---
 - name: install datebase
   yum: name=mariadb-server state=present

 - name: firewall permit
   shell: firewall-cmd --permanent --add-service=mysql
   notify: firewalld_reload

 - name: installing DB modules
   yum: name=MySQL-python state=present

 - name: start mariadb service
   shell: systemctl start mariadb

 - name: enable mariadb service
   shell: systemctl enable mariadb

 - name: restrict access to backend host
   firewalld: port=3306/tcp source={{hostvars[item].ansible_eth1.ipv4.address}}/32 permanent=true state=enabled
   with_items: "{{ groups['backend'] }}"

 - name: set root password
   mysql_user: name=root password='{{db_root_password}}' check_implicit_admin: true 

 - name: create DB proddb
   mysql_db: name={{db_name}} state=present login_user=root login_password={{db_root_password}}

 - name: create DB user
   mysql_user: 
     login_user: root 
     login_password: '{{db_root_password}}'
     name: '{{name_user}}'
     password: '{{password_user}}'
     priv: '*.*:ALL,GRANT'
     host: '{{hostvars[inventory_hostname].ansible_fqdn}}'
     state: present
     check_implicit_admin: yes
   with_items: "{{ groups['backend'] }}"

 - name: modify wordpress database access
   template: src=wp-config.php.j2 dest=/var/wordpress.files/wp-config.php
