---
 - name: install datebase
   yum: name=mariadb-server state=present

 - name: permit DB in firewall
   firewalld: zone=public port=3306/tcp permanent=true state=enabled
   notify: firewalld_reload

 - name: installing DB modules
   yum: name=MySQL-python state=present
   notify: database_start

 - name: start mariadb service
   shell: systemctl start mariadb

 - name: enable mariadb service
   shell: systemctl enable mariadb

 - name: restrict access to backend host
   firewalld: port=3306/tcp source={{hostvars[item].ansible_eth1.ipv4.address}}/32 permanent=true state=enabled
   with_items: "{{ groups['backend'] }}"

 - name: create DB proddb
   mysql_db: name={{db_name}} state=present login_user=root login_password=""

 - name: create DB user
   mysql_user: 
     login_user: root 
     name: '{{name_user}}'
     password: '{{password_user}}'
     priv: '*.*:ALL,GRANT'
     state: present
     check_implicit_admin: yes

 - name: set root password
   mysql_user: login_user=root check_implicit_admin=yes name=root password={{db_root_password}} state=present
