---
 - name: install datebase
   yum: name={{item}} state=present
   with_items:
     - mariadb-server
     - MySQL-python

 - name: start mariadb service
   service: name=mariadb enabled=yes state=started

 - name: restrict access to backend host
   firewalld: service=mysql source={{hostvars[item].ansible_eth1.ipv4.address}}/32 permanent=true state=enabled immediate=true
   with_items: "{{ groups['backend'] }}"

 - name: set root password
   mysql_user: name=root password='{{db_root_password}}' check_implicit_admin=true 
   ignore_errors: true

 - name: create DB proddb
   mysql_db: name={{db_name}} state=present login_user=root login_password={{db_root_password}}

 - name: create DB user
   mysql_user: 
     login_user: root 
     login_password: '{{db_root_password}}'
     name: '{{name_user}}'
     password: '{{password_user}}'
     priv: '*.*:ALL,GRANT'
     host: '{{hostvars[item].ansible_fqdn}}'
     state: present
     check_implicit_admin: yes
   with_items: "{{ groups['backend'] }}"

 - name: modify wordpress database access
   template: src=wp-config.php.j2 dest=/var/wordpress.files/wp-config.php mode=0777 owner=deployer group=deployer
