---

 - name: installing nfs
   yum: name=nfs-utils state=present

 - name: enable nfs service
   service: name=nfs-server state=started enabled=yes

 - name: Create mountable dir
   file: path={{nfs_directory}} state=directory mode=0777 owner=nfsnobody group=nfsnobody

 - name: update the nfs config file
   template:
     src: exports.j2
     dest: /etc/exports

 - name: update the nfs settings
   shell: exportfs -a

 - name: firewall permit
   firewalld: service=nfs permanent=true state=enabled immediate=true

 - name: install rsync
   yum: name=rsync state=present

 - name: wordpress download file
   get_url: url=http://wordpress.org/latest.tar.gz dest=/var/tmp/latest.tar.gz mode=0777
   
 - name: unzip the tar archive
   unarchive: src=/var/tmp/latest.tar.gz dest=/var/tmp/ mode=0777 owner=deployer group=deployer

 - name: copy files to nfs directory
   shell: rsync -avP /var/tmp/wordpress/ /var/wordpress.files

 - name: create uploads directory
   file: path=/var/wordpress.files/wp-content/uploads state=directory mode=0777 owner=deployer group=deployer
