---

 - name: installing nfs
   yum: name=nfs-utils state=present

 - name: enable nfs service
   shell: systemctl enable nfs-server.service

 - name: start nfs service
   shell: systemctl start nfs-server.service

 - name: Create mountable dir
   file: path={{nfs_directory}} state=directory mode=0777 owner=nfsnobody group=nfsnobody

 - name: update the nfs config file
   template:
     src: exports.j2
     dest: /etc/exports

 - name: update the nfs settings
   shell: exportfs -a

 - name: firewall permit
   shell: firewall-cmd --permanent --add-service=nfs

 - name: firewall reload
   shell: firewall-cmd --reload

 - name: install rsync
   yum: name=rsync state=present

 - name: wordpress download file
   get_url: url=http://wordpress.org/latest.tar.gz dest=/var/tmp/ mode=0755
   
 - name: unzip the tar archive
   shell: tar xzvf /var/tmp/latest.tar.gz

 - name: copy files to nfs directory
   shell: rsync -avP /var/tmp/wordpress/ /var/wordpress.files

 - name: create uploads directory
   file: path=/var/wordpress.files/wp-content/uploads state=directory mode=0777 owner=deployer group=deployer
