---
 - name: install nginx
   yum: name=nginx state=present

 - name: modify configuration
   template:
     src: haproxy.cfg.j2
     dest: /etc/nginx/conf.d/beckend.conf 

 - name: modify nginx configuration file
   template:
     src: nginx.conf.j2
     dest: /etc/nginx/nginx.conf
   notify: restart_nginx

 - name: firewalld permit http
   firewalld: service=http permanent=true state=enabled                          
   notify: firewalld_reload

 - name: enable nginx
   service: name=nginx enabled=yes state=started
